version: '2' #使用docker-compose版本
services: #服务
  mysql: #数据库服务
    image: mysql:8 #镜像源
    volumes: #数据卷,挂载目录
      - ../mysql/data:/var/lib/mysql #mysql数据库数据文件存放目录;宿主机目录:容器目录
      - ../docker/mysql/shared:/var/lib/mysql_shared #与php共享目录
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql #数据库初始化sql
    ports: #与宿主进的端口映射   注意缩进，ports要和volumes同齐,下面的- 3306:3306也要和ports平齐
    - 33060:3306 #宿主机端口:容器端口
    restart: always #异常退出后重启
    command: --default-authentication-plugin=mysql_native_password #启动执行指令
    environment: #容器中环境变量
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} #数据库root用户密码
      MYSQL_DATABASE: ${DB_DATABASE} #新创建数据库名称
#      MYSQL_USER: ${DB_USERNAME} #数据库用户名
#      MYSQL_PASSWORD: ${DB_PASSWORD} #数据库密码
  redis: #redis服务
    build: ./redis #Dockerfile源码编译
    restart: always #异常退出后自动重启服务
    command: > #设置redis启动密码
      --requirepass ${REDIS_PASSWORD}
    environment: #容器中环境变量
      REDIS_PASSWORD: ${REDIS_PASSWORD}
#   这里的端口映射改为在Dockerfile中配置
    ports:
    - 63790:6379
    volumes:
      - ../docker/redis/data:/data #redis数据文件存放目录
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  php: #用于本地环境
    build: ./php
    #image: php:7.4-fpm #镜像源
    depends_on: #启动依赖
      - redis
      - mysql
    volumes:
      - ../:/var/www/laravel/xzq-laravel #代码目录 最终解析代码的地方
      - ./php/cron:/var/spool/cron/crontabs/root # 定时任务计划
      - ./php/ini/php.ini:/usr/local/etc/php/php.ini #php配置文件
      - ./php/ini/www.conf:/usr/local/etc/php-fpm.d/www.conf # php-fpm配置文件
#      - ./docker/php/config.json:/root/.composer/config.json #全局镜像源
      - ../docker/mysql/shared:/var/lib/mysql_shared #与mysql共享目录
      - ~/.ssh:/root/.ssh #秘钥挂载方便拉取代码
      - ~/.composer:/root/.composer #compoer全局安装包
    links: #服务之间的hosts绑定访问
      - mysql:db #服务名:别名
      - redis:redis
    restart: always
    environment:
      - DOCKER_APP_ENV=${APP_ENV}
    #这里做域名的映射，地址可以映射到外部主机
    extra_hosts:
      - "local.xzq-laravel.com:host-gateway"
  nginx: #服务器服务
    image: nginx:1.15
    depends_on:
      - php
    volumes:
      - ../:/var/www/laravel/xzq-laravel # 主目录 ps:这里代码只做存放，真正执行是在php容器中，因为最终转发到了phpfpm上
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/vhost:/etc/nginx/conf.d/vhost
    ports:
      - 80:80
      - 443:443
    restart: always
    links:
      - php:phpfpm
